### ISSUE TITLE
Hello Sense sensor?

### ISSUE THREAD

**Issue by rogierdejong** [robbiet480/Home-Assistant-Config#1]
I see you have linked your Hello Sense to your Home Assistant. Great! 
However, I Can't find any information on that anywhere in the internet. Can you tell me how to get the access token?

**Comment by robbiet480** [comment]
You need to follow the steps under "Authorisation" in [this](https://www.chameth.com/2016/04/10/sense-api/) guide. You should run a command like this: `curl -X POST -d "grant_type=password&client_id=8d3c1664-05ae-47e4-bcdb-477489590aa4&client_secret=4f771f6f-5c10-4104-bbc6-3333f5b11bf9&username=YOUREMAIL&password=YOURPASSWORD" https://api.hello.is/v1/oauth2/token`, replacing `YOUREMAIL` and `YOURPASSWORD` with the correct values. Doing that will output an `access_token` which is valid for one year.

**Comment by rogierdejong** [comment]
thanks! I got it working!
